name: Deploy Docs site to Pages
on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - ".github/workflows/deployDocs.yml"
  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# 只允许同时进行一次部署，跳过正在运行和最新队列之间的运行队列
# 但是，不要取消正在进行的运行，因为我们希望允许这些生产部署完成
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # - name: Setup Pages
      #   uses: actions/configure-pages@v4

      - name: Install dependencies
        run: |
          npm i
      - name: Build with VitePress
        run: |
          npm run docs:build
          npm run docs:build:sub
      #    cd "docs/.vitepress"
      #    tar -zcvf dist.tar.gz ./dist
      #    tar -zcvf dist-sub-krpalite.tar.gz ./dist-sub-krpalite
      # - name: Upload pages artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     path: docs/.vitepress/dist
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VitePress-artifact
          path: |
            .github/scripts/frpc.sh
            docs/.vitepress/dist
            docs/.vitepress/dist-sub-krpalite
      #      docs/.vitepress/dist.tar.gz
      #      docs/.vitepress/dist-sub-krpalite.tar.gz

  # 部署 GitHub Pages
  # deploy-github-pages:
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   needs: build
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
  #       continue-on-error: true  # 即使失败，也继续下一个步骤

  # 部署到服务器
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download project files
        uses: actions/download-artifact@v4
        with:
          name: VitePress-artifact

      - name: Run FRPC
        env:
          FRP_CONFIG: ${{ secrets.FRP_CLIENT_CONFIG }}
        run: |
          chmod +x .github/scripts/frpc.sh
          sh .github/scripts/frpc.sh

      - name: Deploy to Centos server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDv -i --delete --no-compress"
          SOURCE: "./docs/.vitepress/dist/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          # EXCLUDE: "dist.tar.gz, dist-sub-krpalite.tar.gz"

      - name: Deploy to local server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.RPALITE_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDv -i --delete --no-compress"
          SOURCE: "./docs/.vitepress/dist/"
          REMOTE_HOST: ${{ secrets.RPALITE_REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.RPALITE_REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.RPALITE_REMOTE_USER }}
          TARGET: ${{ secrets.RPALITE_TARGET }}

      - name: Deploy sub to local server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.RPALITE_SSH_PRIVATE_KEY }}
          ARGS: "-rlgoDv -i --delete --no-compress"
          SOURCE: "./docs/.vitepress/dist-sub-krpalite/"
          REMOTE_HOST: ${{ secrets.RPALITE_REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.RPALITE_REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.RPALITE_REMOTE_USER }}
          TARGET: ${{ secrets.RPALITE_SUB_TARGET }}

      # - name: Deploy dist.tar.gz
      #   uses: easingthemes/ssh-deploy@main
      #   with:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #     ARGS: "-rlgoDvWP -i --no-compress"
      #     SOURCE: "dist.tar.gz dist-sub-krpalite.tar.gz"
      #     REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
      #     REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
      #     REMOTE_USER: ${{ secrets.REMOTE_USER }}
      #     TARGET: ${{ secrets.TARGET }}
      #     EXCLUDE: "/dist/, /docs/.vitepress/dist/, /node_modules/"
      # continue-on-error: true  # 即使失败，也继续下一个步骤

      # - name: Deploy dist
      #   uses: appleboy/ssh-action@v1.2.1
      #   env:
      #     TARGET: ${{ secrets.TARGET }}
      #   with:
      #     host: ${{ secrets.REMOTE_HOST }}
      #     username: ${{ secrets.REMOTE_USER }}
      #     port: ${{ secrets.REMOTE_PORT }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       whoami
      #       cd $TARGET
      #       find . -mindepth 1 ! -name 'dist*.tar.gz' -exec rm -rf {} +
      #       tar -xvf dist.tar.gz --strip-components 2

      # - name: Deploy local dist
      #   env:
      #     HOST_URL: ${{ secrets.DEPLOY_WEBHOOK_HOST_URL }}
      #     API_KEY: ${{ secrets.DEPLOY_WEBHOOK_API_KEY }}
      #     DIST_URL: ${{ secrets.DEPLOY_WEBHOOK_DIST_URL }}
      #     TARGET: ${{ secrets.DEPLOY_WEBHOOK_TARGET }}
      #     DIST_SUB_URL: ${{ secrets.DEPLOY_WEBHOOK_DIST_SUB_URL }}
      #     SUB_TARGET: ${{ secrets.DEPLOY_WEBHOOK_SUB_TARGET }}
      #   run: |
      #     curl --location "$HOST_URL" \
      #       --max-time 900 \
      #       --header 'Content-Type: application/json' \
      #       --header "Authorization: Bearer $API_KEY" \
      #       --data "{
      #           \"url\": \"$DIST_URL\",
      #           \"target\": \"$TARGET\"
      #       }"
      #     curl --location "$HOST_URL" \
      #       --max-time 900 \
      #       --header 'Content-Type: application/json' \
      #       --header "Authorization: Bearer $API_KEY" \
      #       --data "{
      #           \"url\": \"$DIST_SUB_URL\",
      #           \"target\": \"$SUB_TARGET\"
      #       }"

  scrape-docs:
    needs: deploy
    runs-on: ubuntu-latest
    name: scrape and push content on Meilisearch instance
    steps:
      - uses: actions/checkout@v4

      - name: Run docs-scraper
        env:
          HOST_URL: ${{ secrets.MEILISEARCH_HOST_URL }}
          API_KEY: ${{ secrets.MEILISEARCH_API_KEY }}
          ZH_CONFIG_FILE_PATH: ${{ github.workspace }}/docs-scraper/k-rpa-lite.zh.docs-scraper.config.json
          ZH_SUB_CONFIG_FILE_PATH: ${{ github.workspace }}/docs-scraper/k-rpa-lite-sub.zh.docs-scraper.config.json
          EN_CONFIG_FILE_PATH: ${{ github.workspace }}/docs-scraper/k-rpa-lite.en.docs-scraper.config.json
          EN_SUB_CONFIG_FILE_PATH: ${{ github.workspace }}/docs-scraper/k-rpa-lite-sub.en.docs-scraper.config.json
        run: |
          echo "抓取中文站点"
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$HOST_URL \
            -e MEILISEARCH_API_KEY=$API_KEY \
            -v $ZH_CONFIG_FILE_PATH:/docs-scraper/config.json \
            donxj/docs-scraper:0.0.1 pipenv run ./docs_scraper config.json

          echo "抓取子中文站点"
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$HOST_URL \
            -e MEILISEARCH_API_KEY=$API_KEY \
            -v $ZH_SUB_CONFIG_FILE_PATH:/docs-scraper/config.json \
            donxj/docs-scraper:0.0.1 pipenv run ./docs_scraper config.json

          echo "抓取英文站点"
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$HOST_URL \
            -e MEILISEARCH_API_KEY=$API_KEY \
            -v $EN_CONFIG_FILE_PATH:/docs-scraper/config.json \
            donxj/docs-scraper:0.0.1 pipenv run ./docs_scraper config.json

          echo "抓取子英文站点"
          docker run -t --rm \
            -e MEILISEARCH_HOST_URL=$HOST_URL \
            -e MEILISEARCH_API_KEY=$API_KEY \
            -v $EN_SUB_CONFIG_FILE_PATH:/docs-scraper/config.json \
            donxj/docs-scraper:0.0.1 pipenv run ./docs_scraper config.json
